version: '3.1'

services:
  postgres:
    image: postgres
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=W5E@YLJz2fk6
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
