server:
    port: 8083
    error:
        include-message: always
        include-binding-errors: always
        include-stacktrace: on_param
        include_exception: false

spring:
    application:
        name: api-gateway

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
jwt:
    secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY