server:
    port: 8081
    error:
        include-message: always
        include-binding-errors: always
        include-stacktrace: on_param
        include_exception: false
spring:
    application:
        name: bookUser
    datasource:
        password: W5E@YLJz2fk6
        url: jdbc:postgresql://localhost:5432/postgres
        username: admin
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
        enabled: true

